spring:
  profiles:
    active: oauth, local, mail
#---
#server:
#  port: 8080
#
#spring:
#  config:
#    activate:
#      on-profile: test
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop #create update none
#    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect